### ISSUE TITLE
TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by ccinv** [nombersDev/casemove#14]
Same problem just like #2 
> IPC test: ping
1.3.1
githubVersion 131
Logged into Steam as ccinv
Connected to GC!
Have Session!
TypeError: Cannot read properties of undefined (reading '970')
    at e.exports.get_def_index (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:922278)
    at e.exports.itemProcessorImageUrl (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:920738)
    at e.exports.handleError (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:917825)
    at e.exports.inventoryConverter (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:918203)
    at fetchItems.convertInventory (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:916009)
    at GlobalOffensive.<anonymous> (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:909174)
    at Object.onceWrapper (node:events:513:28)
    at GlobalOffensive.emit (node:events:394:28)
    at GlobalOffensive.handlers.<computed> (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\node_modules\globaloffensive\handlers.js:50:7)
    at SteamUser.<anonymous> (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\node_modules\globaloffensive\index.js:51:12)
TypeError: Cannot read properties of undefined (reading '970')
    at e.exports.get_def_index (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:922278)
    at e.exports.itemProcessorName (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:919490)
    at e.exports.handleError (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:917825)
    at e.exports.inventoryConverter (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:918267)
    at fetchItems.convertInventory (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:916009)
    at GlobalOffensive.<anonymous> (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:909174)
    at Object.onceWrapper (node:events:513:28)
    at GlobalOffensive.emit (node:events:394:28)
    at GlobalOffensive.handlers.<computed> (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\node_modules\globaloffensive\handlers.js:50:7)
    at SteamUser.<anonymous> (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\node_modules\globaloffensive\index.js:51:12)

**Comment by ccinv** [comment]
version with issue is 1.3.1, and it never works.
I rolled back to 1.2.1 and it works again. Some changes in price likely break the fix.

**Comment by nombersDev** [comment]
Could you please try again with version 1.4.2? 

With the pricing release the app tried to fetch prices from Google, which of course is blocked in China. I've added backup currencies in case it fails. I'm not 100% certain that this is the root cause, but it might be.

**Comment by ccinv** [comment]
It's good now.
Thanks for doing all these for people in gfw..
