### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by ccinv** [nombersDev/casemove#2]
Do casemove support proxy to steamcommunity? In China steam community is banned and only available through proxy.

**Comment by nombersDev** [comment]
I'm not aware of how China bans Steam specifically, so this is just my best guess. It doesn't interact with the Steam Community per se, and so if you can use the Steam Client regularly / the inventory in game without any proxies, then it should be fine.

**Comment by ccinv** [comment]
When logging in, it raises following error, is it proxy relevant?  
> Logged into Steam as ccinv
Connected to GC!
Have Session!
TypeError: Cannot read properties of undefined (reading '970')
    at e.exports.get_def_index (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:693946)
    at e.exports.itemProcessorImageUrl (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:692451)
    at e.exports.handleError (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:689990)
    at e.exports.inventoryConverter (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:690284)
    at fetchItems.convertInventory (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:688402)
    at GlobalOffensive.<anonymous> (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:696880)
    at Object.onceWrapper (node:events:513:28)
    at GlobalOffensive.emit (node:events:394:28)
    at GlobalOffensive.handlers.<computed> (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\node_modules\globaloffensive\handlers.js:50:7)
    at SteamUser.<anonymous> (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\node_modules\globaloffensive\index.js:51:12)
TypeError: Cannot read properties of undefined (reading '970')
    at e.exports.get_def_index (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:693946)
    at e.exports.itemProcessorName (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:691460)
    at e.exports.handleError (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:689990)
    at e.exports.inventoryConverter (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:690348)
    at fetchItems.convertInventory (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:688402)
    at GlobalOffensive.<anonymous> (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:696880)
    at Object.onceWrapper (node:events:513:28)
    at GlobalOffensive.emit (node:events:394:28)
    at GlobalOffensive.handlers.<computed> (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\node_modules\globaloffensive\handlers.js:50:7)
    at SteamUser.<anonymous> (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\node_modules\globaloffensive\index.js:51:12)
Error
(node:4200) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading '970')
    at e.exports.get_def_index (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:693946)
    at e.exports.inventoryConverter (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:690448)
    at fetchItems.convertInventory (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:688402)
    at GlobalOffensive.<anonymous> (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:696880)
    at Object.onceWrapper (node:events:513:28)
    at GlobalOffensive.emit (node:events:394:28)
    at GlobalOffensive.handlers.<computed> (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\node_modules\globaloffensive\handlers.js:50:7)
    at SteamUser.<anonymous> (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\node_modules\globaloffensive\index.js:51:12)
    at SteamUser.emit (node:events:394:28)
    at SteamUser.<anonymous> (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\node_modules\steam-user\components\gamecoordinator.js:82:8)
(node:4200) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
[18764:0208/095732.035:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is disabled, ANGLE is

**Comment by ccinv** [comment]
It works! Thanks.

**Comment by ccinv** [comment]
Well, logging in is successful. But inventory display is broken. Bunch of errors as follows

> Error
{
  attribute: [
    { def_index: 75, value: null, value_bytes: <Buffer 00 af 0c 62> },
    { def_index: 113, value: null, value_bytes: <Buffer f5 12 00 00> }
  ],
  equipped_state: [],
  id: '24850314641',
  account_id: 129837327,
  inventory: 3221225475,
  def_index: 1209,
  quantity: 1,
  level: 1,
  quality: 4,
  flags: 0,
  origin: 23,
  custom_name: null,
  custom_desc: null,
  interior_item: null,
  in_use: false,
  style: null,
  original_id: null,
  rarity: 4,
  position: 0,
  tradable_after: 2022-02-16T08:00:00.000Z,
  stickers: [
    {
      slot: 0,
      sticker_id: 4853,
      wear: null,
      scale: null,
      rotation: null
    }
  ]
}
TypeError: Cannot read properties of undefined (reading '1209')
    at e.exports.get_def_index (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:498810)
    at e.exports.itemProcessorCanBeMoved (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:497938)
    at e.exports.handleError (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:494443)
    at e.exports.inventoryConverter (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:495536)
    at fetchItems.convertInventory (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:492905)
    at GlobalOffensive.<anonymous> (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\dist\main\main.js:8:486969)
    at Object.onceWrapper (node:events:513:28)
    at GlobalOffensive.emit (node:events:394:28)
    at GlobalOffensive.handlers.<computed> (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\node_modules\globaloffensive\handlers.js:50:7)
    at SteamUser.<anonymous> (C:\Users\avaic\AppData\Local\Programs\casemove\resources\app.asar\node_modules\globaloffensive\index.js:51:12)

**Comment by ccinv** [comment]
It is fixed in 1.1.2. Thanks.
